// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rpc} from '../models';
import {storage} from '../models';
import {main} from '../models';
import {logger} from '../models';
import {context} from '../models';

export function CancelReflection():Promise<void>;

export function CancelStream():Promise<void>;

export function CancelUnary():Promise<void>;

export function ClearHistory(arg1:string):Promise<void>;

export function ClearLoadedProtos():Promise<void>;

export function ClearLogs():Promise<void>;

export function Connect(arg1:rpc.ConnectionConfig):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportCollection(arg1:string,arg2:string):Promise<void>;

export function GetCollection(arg1:string):Promise<storage.Collection>;

export function GetConnectionState():Promise<string>;

export function GetHistory(arg1:string):Promise<Array<storage.HistoryEntry>>;

export function GetLoadedState():Promise<main.LoadedState>;

export function GetLogs(arg1:string):Promise<Array<logger.Entry>>;

export function GetRequestSchema(arg1:string):Promise<Array<rpc.FieldSchema>>;

export function GetServices():Promise<Array<rpc.ServiceInfo>>;

export function GetUserSettings():Promise<main.UserSettings>;

export function GetVersion():Promise<string>;

export function ImportCollection(arg1:string):Promise<storage.Collection>;

export function InvokeStream(arg1:rpc.InvokeRequest):Promise<void>;

export function InvokeUnary(arg1:rpc.InvokeRequest):Promise<rpc.InvokeResponse>;

export function ListCollections():Promise<Array<storage.Collection>>;

export function ListEnvironments():Promise<Array<storage.Environment>>;

export function LoadProtoFiles(arg1:Array<string>,arg2:Array<string>):Promise<Array<rpc.ServiceInfo>>;

export function LoadProtosets(arg1:Array<string>):Promise<Array<rpc.ServiceInfo>>;

export function LoadViaReflection():Promise<Array<rpc.ServiceInfo>>;

export function PickDirectory():Promise<string>;

export function PickExportPath(arg1:string):Promise<string>;

export function PickImportFile():Promise<string>;

export function PickProtoFiles():Promise<Array<string>>;

export function PickProtosetFiles():Promise<Array<string>>;

export function ReloadProtos():Promise<Array<rpc.ServiceInfo>>;

export function RemoveProtoPath(arg1:string):Promise<Array<rpc.ServiceInfo>>;

export function SaveCollection(arg1:storage.Collection):Promise<void>;

export function SaveEnvironment(arg1:storage.Environment):Promise<void>;

export function SaveUserSettings(arg1:main.UserSettings):Promise<void>;

export function SaveWindowState(arg1:context.Context):Promise<void>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function TriggerMenuAbout():Promise<void>;

export function TriggerMenuCloseAllTabs():Promise<void>;

export function TriggerMenuCloseTab():Promise<void>;

export function TriggerMenuExport():Promise<void>;

export function TriggerMenuHelp():Promise<void>;

export function TriggerMenuImport():Promise<void>;

export function TriggerMenuNewTab():Promise<void>;

export function TriggerMenuNextTab():Promise<void>;

export function TriggerMenuPrevTab():Promise<void>;

export function TriggerMenuToggleDebugPane():Promise<void>;

export function TriggerMenuZoomIn():Promise<void>;

export function TriggerMenuZoomOut():Promise<void>;

export function TriggerMenuZoomReset():Promise<void>;
