// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelReflection() {
  return window['go']['main']['App']['CancelReflection']();
}

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function CancelUnary() {
  return window['go']['main']['App']['CancelUnary']();
}

export function ClearHistory(arg1) {
  return window['go']['main']['App']['ClearHistory'](arg1);
}

export function ClearLoadedProtos() {
  return window['go']['main']['App']['ClearLoadedProtos']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportCollection(arg1, arg2) {
  return window['go']['main']['App']['ExportCollection'](arg1, arg2);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetConnectionState() {
  return window['go']['main']['App']['GetConnectionState']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetLoadedState() {
  return window['go']['main']['App']['GetLoadedState']();
}

export function GetRequestSchema(arg1) {
  return window['go']['main']['App']['GetRequestSchema'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetUserSettings() {
  return window['go']['main']['App']['GetUserSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportCollection(arg1) {
  return window['go']['main']['App']['ImportCollection'](arg1);
}

export function InvokeStream(arg1) {
  return window['go']['main']['App']['InvokeStream'](arg1);
}

export function InvokeUnary(arg1) {
  return window['go']['main']['App']['InvokeUnary'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function LoadProtoFiles(arg1, arg2) {
  return window['go']['main']['App']['LoadProtoFiles'](arg1, arg2);
}

export function LoadProtosets(arg1) {
  return window['go']['main']['App']['LoadProtosets'](arg1);
}

export function LoadViaReflection() {
  return window['go']['main']['App']['LoadViaReflection']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickExportPath(arg1) {
  return window['go']['main']['App']['PickExportPath'](arg1);
}

export function PickImportFile() {
  return window['go']['main']['App']['PickImportFile']();
}

export function PickProtoFiles() {
  return window['go']['main']['App']['PickProtoFiles']();
}

export function PickProtosetFiles() {
  return window['go']['main']['App']['PickProtosetFiles']();
}

export function ReloadProtos() {
  return window['go']['main']['App']['ReloadProtos']();
}

export function RemoveProtoPath(arg1) {
  return window['go']['main']['App']['RemoveProtoPath'](arg1);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveUserSettings(arg1) {
  return window['go']['main']['App']['SaveUserSettings'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function TriggerMenuAbout() {
  return window['go']['main']['App']['TriggerMenuAbout']();
}

export function TriggerMenuCloseAllTabs() {
  return window['go']['main']['App']['TriggerMenuCloseAllTabs']();
}

export function TriggerMenuCloseTab() {
  return window['go']['main']['App']['TriggerMenuCloseTab']();
}

export function TriggerMenuExport() {
  return window['go']['main']['App']['TriggerMenuExport']();
}

export function TriggerMenuHelp() {
  return window['go']['main']['App']['TriggerMenuHelp']();
}

export function TriggerMenuImport() {
  return window['go']['main']['App']['TriggerMenuImport']();
}

export function TriggerMenuNewTab() {
  return window['go']['main']['App']['TriggerMenuNewTab']();
}

export function TriggerMenuNextTab() {
  return window['go']['main']['App']['TriggerMenuNextTab']();
}

export function TriggerMenuPrevTab() {
  return window['go']['main']['App']['TriggerMenuPrevTab']();
}

export function TriggerMenuToggleFullscreen() {
  return window['go']['main']['App']['TriggerMenuToggleFullscreen']();
}

export function TriggerMenuZoomIn() {
  return window['go']['main']['App']['TriggerMenuZoomIn']();
}

export function TriggerMenuZoomOut() {
  return window['go']['main']['App']['TriggerMenuZoomOut']();
}

export function TriggerMenuZoomReset() {
  return window['go']['main']['App']['TriggerMenuZoomReset']();
}
